#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-appraisal
Version  : 2.1.0
Release  : 15
URL      : https://rubygems.org/downloads/appraisal-2.1.0.gem
Source0  : https://rubygems.org/downloads/appraisal-2.1.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-appraisal-bin
BuildRequires : ruby
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-appraisal
BuildRequires : rubygem-bundler
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-i18n
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-rubygems-tasks
BuildRequires : rubygem-thor
BuildRequires : rubygem-tzinfo
Patch1: 0001-Fix-thor-version.patch

%description
Appraisal
=========
[![Build Status][Build Status Image]][Build Status]
Find out what your Ruby gems are worth.

%package bin
Summary: bin components for the rubygem-appraisal package.
Group: Binaries

%description bin
bin components for the rubygem-appraisal package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n appraisal-2.1.0
gem spec %{SOURCE0} -l --ruby > rubygem-appraisal.gemspec
%patch1 -p1

%build
export LANG=C
gem build rubygem-appraisal.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
appraisal-2.1.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/appraisal-2.1.0
rspec -I.:lib spec/ || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/appraisal-2.1.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/.rspec
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/appraisal.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/bin/appraisal
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal/appraisal.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal/bundler_dsl.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal/cli.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal/command.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal/dependency.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal/dependency_list.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal/errors.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal/file.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal/gemfile.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal/gemspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal/git_source.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal/group.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal/ordered_hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal/path_source.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal/platform.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal/source.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal/task.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal/travis_ci_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal/utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/lib/appraisal/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/acceptance/appraisals_file_bundler_dsl_compatibility_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/acceptance/bundle_with_custom_path_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/acceptance/cli/clean_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/acceptance/cli/generate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/acceptance/cli/help_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/acceptance/cli/install_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/acceptance/cli/list_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/acceptance/cli/run_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/acceptance/cli/update_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/acceptance/cli/version_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/acceptance/cli/with_no_arguments_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/acceptance/gemfile_dsl_compatibility_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/acceptance/gemspec_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/acceptance/travis_ci_integration_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/appraisal/appraisal_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/appraisal/dependency_list_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/appraisal/file_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/appraisal/gemfile_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/appraisal/utils_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/support/acceptance_test_helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/support/dependency_helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/appraisal-2.1.0/spec/support/stream_helpers.rb
/usr/lib64/ruby/gems/2.3.0/specifications/appraisal-2.1.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/appraisal
